name: syrix_chat
description: SYRIX CHAT mobile app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  web_socket_channel: ^3.0.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  flutter_linkify: ^6.0.0
  livekit_client: ^2.3.4
  permission_handler: ^11.3.1
  record: ^7.1.1
  audioplayers: ^6.1.0
  path_provider: ^2.1.3
  crypto: ^3.0.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  gallery_saver_plus: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
